[project]
name = "RL-implementations"
version = "0.1.0"
description = "Practicing implementing some RL algorithms in pytorch"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gymnasium[box2d]>=1.2.2",
    "torch>=2.9.0",
]
